const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      borderRadius: {
        none: "0",
        xs: "0.375rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        section: "2.5rem",
        full: "9999px",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        border: "hsl(var(--border))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
      },
      fontFamily: {
        sans: ["CommitMono", ...defaultTheme.fontFamily.mono],
        serif: ["CommitMono", ...defaultTheme.fontFamily.mono],
        mono: ["CommitMono", ...defaultTheme.fontFamily.mono],
      },
      fontSize: {
        base: ["12px", { lineHeight: "20px" }],
      },
      listStyleType: {
        square: "square",
      },
      maxWidth: (theme) => theme("spacing"),
      minWidth: (theme) => theme("spacing"),
      maxHeight: (theme) => theme("spacing"),
      minHeight: (theme) => theme("spacing"),
      screens: {
        xs: "340px",
        sm: "540px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        xxl: "1460px",
        "pointer-fine": { raw: "(pointer: fine)" },
      },
      spacing: {
        0: "0",
        px: "1px",
        0.125: "0.125rem",
        0.25: "0.25rem",
        0.5: "0.5rem",
        0.75: "0.75rem",
        1: "1rem",
        1.5: "1.5rem",
        2: "2rem",
        2.5: "2.5rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        8: "8rem",
        12: "12rem",
        16: "16rem",
        20: "20rem",
        24: "24rem",
        32: "32rem",
        40: "40rem",
        48: "48rem",
        64: "64rem",
        "1lh": "20px",
        "2lh": "40px",
        "3lh": "60px",
      },
    },
  },
  plugins: [],
};
